// <auto-generated />
namespace Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixContributorID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixContributorID));
        
        string IMigrationMetadata.Id
        {
            get { return "201810020531204_fixContributorID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
